# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c
script: ./travis-tool.sh run_tests
env:
   global:
     - R_BUILD_ARGS="--no-build-vignettes --no-manual --keep-empty-dirs"
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - rm ProjectTemplate_*.*.tar.gz
install:
  - ./travis-tool.sh r_binary_install colorspace RColorBrewer dichromat munsell labeling Formula sp mvtnorm TH.data sandwich formatR highr markdown zoo bit gtable reshape2 scales proto quantreg Hmisc mapproj maps hexbin maptools multcomp knitr DBI RUnit gtools signal pastecs chron fastmatch xts
  - ./travis-tool.sh aptget_install unixodbc-dev
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package assertthat
notifications:
  email:
    on_success: change
    on_failure: change
