# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: java
script: ./travis-tool.sh run_tests
env:
   global:
     - R_BUILD_ARGS="--no-build-vignettes --no-manual --keep-empty-dirs"
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - rm ProjectTemplate_*.*.tar.gz
install:
  - ./travis-tool.sh r_binary_install colorspace RColorBrewer dichromat munsell labeling Formula sp mvtnorm TH.data sandwich formatR highr markdown zoo bit gtable reshape2 scales proto quantreg Hmisc mapproj maps hexbin maptools multcomp knitr DBI RUnit gtools signal pastecs chron fastmatch xts reshape ggplot2 lubridate RMySQL RSQLite gdata RODBC pixmap data.table
  - ./travis-tool.sh aptget_install unixodbc-dev
  - sudo R CMD javareconf
  - ./travis-tool.sh install_deps
  - Rscript -e "library(RJDBC); library(xlsx); library(RODBC)"
notifications:
  email:
    on_success: change
    on_failure: always
